### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by cjbrock** [learn-co-curriculum/has-many-through-forms-rails-labs#11]
PROBLEM: The solution to this project was deleted because it was no longer accurate. It needs to be updated for the project, and uploaded. 

NOTIFY:
@thekevinhuang
@bhollan
@danblondell
@BuffaloRob
@kyle-poretto

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
