### ISSUE TITLE
readme bullets/numbers show up wrong in the browser

### ISSUE THREAD

**Issue by jd2rogers2** [learn-co-curriculum/has-many-through-forms-rails-labs#14]
<img width="1062" alt="Screen Shot 2019-08-09 at 8 41 23 PM" src="https://user-images.githubusercontent.com/16400333/62815489-6965c600-bae7-11e9-80e2-14d17183741c.png">

**Comment by drakeltheryuujin** [comment]
Thanks for pointing out this markdown issue. I've updated the materials and the display should be working properly.
