### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by HuydDo** [learn-co-curriculum/has-many-through-forms-rails-labs#19]
(https://apidock.com/rails/ActionView/Helpers/FormHelper/hiddenfield)_:

**Comment by rrcobb** [comment]
When I visit the url at https://apidock.com/rails/ActionView/Helpers/FormHelper/hidden_field I find a working documentation page for the hidden_field method. 

If I'm not understanding the issue correctly, please reopen with additional context (a line number would be helpful if there's an issue in the README!
